modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
[[mods]]
modId = "claysoldiers2"
version = "${file.jarVersion}"
displayName = "Clay Soldiers 2"
logoFile = "ClaySoldiers2Logo.png"
credits = "Made by MultiTeam"
authors = "LazTheArtist [Code - Art]"
description = '''
Those good old days, when we had little clay people running around in our worlds... we all miss them.
But not anymore! Here comes the reboot! But, unlike the Ben10 reboot, this one doesnt suck!

Clay Soldiers 2 brings most features from the original mod to a modern version of minecraft, whilst expanding upon the features and basically improving the whole thing!
'''
[[dependencies.claysoldiers2]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.claysoldiers2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.claysoldiers2]]
modId = "multicore_lib"
mandatory = true
versionRange = "[1.18.2-0.3.0.0,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.claysoldiers2]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.3,)"
ordering = "AFTER"
side = "BOTH"
